### PR TITLE
Buttonfix

### PR DESCRIPTION
**Pull request by Twilliams19**
Here is my new button fix

### CODE REVIEW

**Review by axecopfire — CHANGES_REQUESTED** [review]
There are 4 files changed here. The button fix needs to only cover 1 file and it should be about a 5 line change.

**Comment by Timestorm** [comment]
Can this pull request contain more specific information to accurately reflect changes?

Maybe include name of the project (Student CSS?)  and a better describe what changes were made.  Because of the lack of description, I originally mistaken this for a fix to Issue #22

**Comment by axecopfire** [comment]
Good feedback. This pull request is supposed to resolve issue #6.

**Comment by axecopfire** [comment]
Please delete .DS_Store file

**Review by axecopfire — APPROVED** [review]

**Pull request merged**
